import os
import sys
import tempfile
import shutil
import asyncio
from unittest.mock import MagicMock
from dotenv import load_dotenv

# Add parent directory to path
sys.path.append(os.path.normpath(os.path.join(os.path.dirname(__file__), "..")))

from core.vision import VisionAnalyzer
from core.orchestrator import DualLoopOrchestrator
from core.memory import SystemContextMemory, AgentMemory
from core.planner import CognitivePlanner
from core.cli_engine import CLIEngine
from core.sandbox import DockerSandbox

def main():
    load_dotenv()
    print("=== Testing J.A.R.V.I.S 10.0 Vision Subsystem ===")
    failed = False

    workspace_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    
    # Create a temporary directory inside the workspace for safe testing files
    temp_test_dir = tempfile.mkdtemp(dir=workspace_dir, prefix="test_vision_run_")
    print(f"Created temporary test directory at: {temp_test_dir}")

    try:
        # 1. Test WebcamCapture default timestamp generation and capture behavior
        print("\n[Test 1] Testing WebcamCapture and timestamp generation...")
        
        # Test default unique timestamp paths in capture_and_analyze
        analyzer = VisionAnalyzer(llm_client=None)
        
        # Mock webcam.capture to see if save_path is populated correctly
        mock_capture = MagicMock(return_value={"success": True, "image_bytes": b"mockjpeg", "save_path": None, "error": None})
        analyzer.webcam.capture = mock_capture
        analyzer.analyze_image = MagicMock(return_value="Mocked VLM analysis response of workspace")
        
        res = analyzer.capture_and_analyze("Capture test")
        print(f"Capture & Analyze result: {res}")
        
        # Verify it passed a save_path with timestamped format like 'webcam_{timestamp}.jpg'
        actual_save_path = mock_capture.call_args[1].get("save_path")
        print(f"Actual saved path used: {actual_save_path}")
        assert actual_save_path is not None
        assert "webcam_" in actual_save_path
        assert actual_save_path.endswith(".jpg")
        print("[SUCCESS] Timestamped path correctly generated by default!")

        # 2. Test prompt sanitization in Orchestrator for action-based queries
        print("\n[Test 2] Testing Orchestrator prompt sanitization and analyze_existing routing...")
        
        # Setup mocks for Orchestrator
        sandbox = DockerSandbox()
        cli_engine = CLIEngine(sandbox)
        sys_memory = SystemContextMemory(workspace_dir)
        agent_memory = AgentMemory("VisionTest")
        planner = CognitivePlanner()
        
        # Write a dummy test image to simulate existing webcam_capture
        dummy_image_filename = "webcam_capture_test_file.jpg"
        dummy_image_path = os.path.join(temp_test_dir, dummy_image_filename)
        with open(dummy_image_path, "wb") as f:
            f.write(b"dummy_image_bytes")
            
        print(f"Wrote dummy image file to: {dummy_image_path}")

        # Set up a mock VLM client
        mock_openai_client = MagicMock()
        
        def mock_chat_completions_create(model, messages, **kwargs):
            user_content = messages[-1]["content"] if messages else ""
            mock_resp = MagicMock()
            mock_choice = MagicMock()
            
            if "Complexity" in user_content or "complexity" in str(user_content).lower():
                mock_choice.message.content = '{"complexity": "COMPLEX", "reason": "Testing complexity"}'
            elif "Validator" in user_content or "validator" in str(user_content).lower():
                mock_choice.message.content = '{"validated": true, "reason": "Output is descriptive and matches expected criteria."}'
            else:
                mock_choice.message.content = "Mocked conversational response from J.A.R.V.I.S."
                
            mock_resp.choices = [mock_choice]
            return mock_resp
            
        mock_openai_client.chat.completions.create.side_effect = mock_chat_completions_create
        
        # Mock VisionAnalyzer
        mock_vision = MagicMock()
        mock_vision.analyze_image = MagicMock(return_value="Visual description: A desk with a laptop, monitor, and notebook.")
        
        # Standardize return dictionary format
        mock_vision.capture_and_analyze = MagicMock(return_value={
            "success": True,
            "analysis": "Visual description of dynamic snapshot",
            "save_path": "webcam_captured_path.jpg",
            "error": None
        })
        
        orchestrator = DualLoopOrchestrator(
            planner=planner,
            cli_engine=cli_engine,
            sys_memory=sys_memory,
            agent_memory=agent_memory,
            llm_client=mock_openai_client,
            vision=mock_vision
        )
        
        # Force workspace root and active locations to resolve relative path
        sys_memory.workspace_root = workspace_dir
        
        # Test 2.1: capture_and_analyze path with "store" action prompt
        step_capture = {
            "id": 1,
            "type": "vision",
            "description": "Capture new webcam",
            "command_or_action": "capture_and_analyze store image of my desk",
            "dependencies": []
        }
        
        # Execute capture step with a clean event loop
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            cap_step_res = loop.run_until_complete(orchestrator._execute_and_validate_step(step_capture))
            print(f"Capture Step Result: {cap_step_res}")
            
            # Verify Vision capture_and_analyze was called with sanitized prompt
            mock_vision.capture_and_analyze.assert_called_once()
            called_prompt = mock_vision.capture_and_analyze.call_args[0][0]
            print(f"Sanitized Prompt passed to capture_and_analyze: '{called_prompt}'")
            assert "Describe this image in detailed visual terms so I can process and store it." in called_prompt
            assert "store image of my desk" in called_prompt
            print("[SUCCESS] capture_and_analyze prompt successfully sanitized!")

            # Test 2.2: analyze_existing path with "update" action prompt
            mock_vision.reset_mock()
            
            step_existing = {
                "id": 2,
                "type": "vision",
                "description": "Analyze existing photo",
                "command_or_action": f"analyze_existing {dummy_image_path} update memory with this picture",
                "dependencies": []
            }
            
            exist_step_res = loop.run_until_complete(orchestrator._execute_and_validate_step(step_existing))
            print(f"Existing Step Result: {exist_step_res}")
            
            # Verify analyze_image was called with sanitized prompt and image bytes, and capture was NOT called
            mock_vision.capture_and_analyze.assert_not_called()
            mock_vision.analyze_image.assert_called_once()
            called_bytes = mock_vision.analyze_image.call_args[0][0]
            called_existing_prompt = mock_vision.analyze_image.call_args[0][1]
            
            print(f"Sanitized Prompt passed to analyze_image: '{called_existing_prompt}'")
            assert called_bytes == b"dummy_image_bytes"
            assert "Describe this image in detailed visual terms so I can process and store it." in called_existing_prompt
            assert "update memory with this picture" in called_existing_prompt
            print("[SUCCESS] analyze_existing successfully resolved file with spaces, read bytes, and sanitized prompt!")

            # Test 2.3: analyze_existing with a path lacking an extension (extension probe fallback)
            mock_vision.reset_mock()
            path_no_ext = dummy_image_path[:-4] # removes '.jpg'
            step_no_ext = {
                "id": 3,
                "type": "vision",
                "description": "Analyze existing photo without extension",
                "command_or_action": f"analyze_existing {path_no_ext} describe this desk",
                "dependencies": []
            }
            no_ext_step_res = loop.run_until_complete(orchestrator._execute_and_validate_step(step_no_ext))
            print(f"No-Extension Step Result: {no_ext_step_res}")
            assert no_ext_step_res.get("success") is True
            mock_vision.analyze_image.assert_called_once()
            called_bytes = mock_vision.analyze_image.call_args[0][0]
            assert called_bytes == b"dummy_image_bytes"
            print("[SUCCESS] analyze_existing successfully probed and resolved file with missing extension!")
        finally:
            loop.close()

        # 3. Test SystemContextMemory screenshot exposure
        print("\n[Test 3] Testing dynamic screenshots exposure in SystemContextMemory...")
        sys_memory_test = SystemContextMemory(temp_test_dir)
        screenshots_dir = os.path.join(temp_test_dir, "capabilities", "screenshots")
        os.makedirs(screenshots_dir, exist_ok=True)
        
        # Write a dummy image to the screenshots directory
        test_img_path = os.path.join(screenshots_dir, "webcam_20260522_155759.jpg")
        with open(test_img_path, "wb") as f:
            f.write(b"dummy_bytes")
            
        compiled_ctx = sys_memory_test.compile_global_context()
        print("Compiled context snippet:")
        print(compiled_ctx)
        
        assert "--- CAPTURED WEBCAM IMAGES & SCREENSHOTS ---" in compiled_ctx
        assert "webcam_20260522_155759.jpg" in compiled_ctx
        print("[SUCCESS] SystemContextMemory successfully indexes and lists captured screenshots in global context!")

    except Exception as e:
        print(f"[ERROR] Test failed with exception: {e}")
        import traceback
        traceback.print_exc()
        failed = True
    finally:
        # Clean up temp files
        if os.path.exists(temp_test_dir):
            shutil.rmtree(temp_test_dir)
            print(f"Cleaned up temporary test directory: {temp_test_dir}")
            
    if failed:
        sys.exit(1)
    else:
        print("\n=== [ALL TESTS PASSED] Vision Subsystem is 100% Correct and Robust! ===")
        sys.exit(0)

if __name__ == "__main__":
    main()
